---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - PersistentVolume
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmap
  - endpoints/restricted
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - secrets
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - leases
  - namespaces
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/eviction
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - get
  - update
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  - dnses
  - infrastructures
  - networks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - console.openshift.io
  resources:
  - consoleplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.ibm.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - csi.ibm.com
  resources:
  - csiscaleoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.ibm.com
  resources:
  - csiscaleoperators/finalizers
  verbs:
  - update
- apiGroups:
  - csi.ibm.com
  resources:
  - csiscaleoperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fusion.storage.openshift.io
  resources:
  - fusionaccesses
  - localvolumediscoveries
  - localvolumediscoveries/status
  - localvolumediscoveryresults
  - localvolumediscoveryresults/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fusion.storage.openshift.io
  resources:
  - fusionaccesses/finalizers
  verbs:
  - update
- apiGroups:
  - fusion.storage.openshift.io
  resources:
  - fusionaccesses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - imageregistry.operator.openshift.io
  resources:
  - configs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kmm.sigs.x-k8s.io
  resources:
  - modules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - oauth.openshift.io
  resources:
  - oauthclients
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - consoles
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - '*'
  - approvalrequests
  - asyncreplications
  - callhomes
  - cloudcsidisks
  - clusters
  - compressionjobs
  - consistencygroups
  - daemons
  - diskjobs
  - dnss
  - encryptionconfigs
  - filesystems
  - grafanabridges
  - guis
  - localdisks
  - pmcollectors
  - recoverygroups
  - remoteclusters
  - restripefsjobs
  - stretchclusterinitnodes
  - stretchclusters
  - stretchclustertiebreaker
  - upgradeapprovals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - '*/finalizers'
  - asyncreplications/finalizers
  - callhomes/finalizers
  - cloudcsidisks/finalizers
  - clusters/finalizers
  - compressionjobs/finalizers
  - daemons/finalizers
  - diskjobs/finalizers
  - dnss/finalizers
  - encryptionconfigs/finalizers
  - filesystems/finalizers
  - grafanabridges/finalizers
  - guis/finalizers
  - localdisks/finalizers
  - pmcollectors/finalizers
  - recoverygroups/finalizers
  - regionaldrexports/finalizers
  - remoteclusters/finalizers
  - restripefsjobs/finalizers
  - stretchclusterinitnodes/finalizers
  - stretchclusters/finalizers
  - stretchclustertiebreaker/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - '*/status'
  - approvalrequests/status
  - asyncreplications/status
  - callhomes/status
  - cloudcsidisks/status
  - clusters/status
  - compressionjobs/status
  - consistencygroups/status
  - daemons/status
  - diskjobs/status
  - dnss/status
  - encryptionconfigs/status
  - guis/status
  - localdisks/status
  - pmcollectors/status
  - recoverygroups/status
  - regionaldrexports/status
  - regionaldrs/finalizers
  - regionaldrs/status
  - remoteclusters/status
  - restripefsjobs/status
  - stretchclusterinitnodes/status
  - stretchclusters/status
  - stretchclustertiebreaker/status
  - upgradeapprovals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - clusterinterconnects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - filesystems/status
  - regionaldrs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - grafanabridges/status
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - regionaldrexports
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  - storageclasses
  - volumeattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: ibm-fusion-access
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
