apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-storage-scale/openshift-fusion-access-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "v1" && (
      "console/***".pathChanged() ||
      "VERSION.txt".pathChanged() ||
      ".tekton/console-plugin-1-0-on-pull-request.yaml".pathChanged() ||
      ".tekton/console-plugin-common.yaml".pathChanged() ||
      "templates/console-plugin.Dockerfile.template".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: operator-1-0
    appstudio.openshift.io/component: console-plugin-1-0
    pipelines.appstudio.openshift.io/type: build
  name: console-plugin-1-0-on-pull-request
  namespace: storage-scale-releng-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/storage-scale-releng-tenant/console-plugin-rhel9:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: console-plugin.Dockerfile
  - name: prefetch-input
    value: [{"type": "npm", "path": "console/"},]
    # TODO switch to yarn at some point
    # {"type": "yarn", "path": "console/"},]
  pipelineRef:
    name: console-plugin-common
  taskRunTemplate:
    serviceAccountName: build-pipeline-console-plugin-1-0
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
